name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake g++-11
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git $GITHUB_WORKSPACE/vcpkg
        $GITHUB_WORKSPACE/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: |
        # Ensure binary exists and is executable
        if [ -f "./build/bin/manifast" ]; then
          chmod +x ./build/bin/manifast
          ./build/bin/manifast tests/Manifast/test.mnf
        else
          echo "Error: manifast binary not found!"
          exit 1
        fi
