name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget software-properties-common
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install -y ninja-build cmake g++-12 llvm-18-dev libfmt-dev libgtest-dev
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        
        # Install argparse manually (header-only)
        sudo mkdir -p /usr/local/include/argparse
        sudo wget -O /usr/local/include/argparse/argparse.hpp https://raw.githubusercontent.com/p-ranav/argparse/master/include/argparse/argparse.hpp

    - name: Configure CMake
      run: |
        # Explicitly tell CMake where to find LLVM Config
        cmake -S . -B build -G "Ninja" \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_DIR=/usr/lib/llvm-18/lib/cmake/llvm
          # No vcpkg toolchain -> uses system libs found by find_package

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: |
        ./build/bin/manifast --test tests/Manifast

